// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4lET8sN-KF51syI50kY1VELkFn0yZKA',
    appId: '1:749176980517:web:4b675649ad33a3dcb06bcc',
    messagingSenderId: '749176980517',
    projectId: 'my-library-41b71',
    authDomain: 'my-library-41b71.firebaseapp.com',
    storageBucket: 'my-library-41b71.appspot.com',
    measurementId: 'G-KY2CXGTMDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Kq70tSJEhybV_StOnBAoi2f-uGwei9U',
    appId: '1:749176980517:android:0f7e0cac067dbf8bb06bcc',
    messagingSenderId: '749176980517',
    projectId: 'my-library-41b71',
    storageBucket: 'my-library-41b71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAka3ul7IShhRJXfhvjRPkAyAbTz_5AO8Y',
    appId: '1:749176980517:ios:0900b3459d6986cab06bcc',
    messagingSenderId: '749176980517',
    projectId: 'my-library-41b71',
    storageBucket: 'my-library-41b71.appspot.com',
    iosClientId: '749176980517-mnqole7qpl2ubnvgglqokahthlf9mv9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAka3ul7IShhRJXfhvjRPkAyAbTz_5AO8Y',
    appId: '1:749176980517:ios:8d9b2ae1867b40b3b06bcc',
    messagingSenderId: '749176980517',
    projectId: 'my-library-41b71',
    storageBucket: 'my-library-41b71.appspot.com',
    iosClientId: '749176980517-elfb03kel6ndagir7c8rg6oe3ul6t2bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myLibrary.RunnerTests',
  );
}

